services:
  api:
    build: .
    container_name: info_market_api
    environment:
      NODE_ENV: development
      API_PORT: ${API_PORT:-3000}
      DATABASE_URL: postgres://${POSTGRES_USER:-info_market_user}:${POSTGRES_PASSWORD:-12345678}@info_market_db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-info_market_db}
      POSTGRES_HOST: ${POSTGRES_HOST:-info_market_db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-info_market_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-info_market_db}
    depends_on:
      info_market_db:
        condition: service_healthy
    ports:
      - "3000:3000"        # host:container
    command: ["node", "dist/main.js"]

  info_market_db:
    container_name: info_market_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_USER: ${POSTGRES_USER:-info_market_user}
      POSTGRES_DB: ${POSTGRES_DB:-info_market_db}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
